/*
 * This file is generated by jOOQ.
 */
package org.tayrona.sakila.data.tables.pojos;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import javax.annotation.Nullable;
import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * Address details table
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "ADDRESS",
    schema = "PUBLIC"
)
public class Address implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long addressId;
    private String address;
    private String address2;
    private String district;
    private Long cityId;
    private String postalCode;
    private String phone;
    private OffsetDateTime lastUpdate;

    public Address() {}

    public Address(Address value) {
        this.addressId = value.addressId;
        this.address = value.address;
        this.address2 = value.address2;
        this.district = value.district;
        this.cityId = value.cityId;
        this.postalCode = value.postalCode;
        this.phone = value.phone;
        this.lastUpdate = value.lastUpdate;
    }

    public Address(
        Long addressId,
        String address,
        @Nullable String address2,
        @Nullable String district,
        Long cityId,
        @Nullable String postalCode,
        String phone,
        OffsetDateTime lastUpdate
    ) {
        this.addressId = addressId;
        this.address = address;
        this.address2 = address2;
        this.district = district;
        this.cityId = cityId;
        this.postalCode = postalCode;
        this.phone = phone;
        this.lastUpdate = lastUpdate;
    }

    /**
     * Getter for <code>PUBLIC.ADDRESS.ADDRESS_ID</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ADDRESS_ID", nullable = false)
    public Long getAddressId() {
        return this.addressId;
    }

    /**
     * Setter for <code>PUBLIC.ADDRESS.ADDRESS_ID</code>.
     */
    public void setAddressId(Long addressId) {
        this.addressId = addressId;
    }

    /**
     * Getter for <code>PUBLIC.ADDRESS.ADDRESS</code>.
     */
    @Column(name = "ADDRESS", nullable = false, length = 50)
    @NotNull
    @Size(max = 50)
    public String getAddress() {
        return this.address;
    }

    /**
     * Setter for <code>PUBLIC.ADDRESS.ADDRESS</code>.
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * Getter for <code>PUBLIC.ADDRESS.ADDRESS2</code>.
     */
    @Column(name = "ADDRESS2", length = 50)
    @Size(max = 50)
    @Nullable
    public String getAddress2() {
        return this.address2;
    }

    /**
     * Setter for <code>PUBLIC.ADDRESS.ADDRESS2</code>.
     */
    public void setAddress2(@Nullable String address2) {
        this.address2 = address2;
    }

    /**
     * Getter for <code>PUBLIC.ADDRESS.DISTRICT</code>.
     */
    @Column(name = "DISTRICT", length = 50)
    @Size(max = 50)
    @Nullable
    public String getDistrict() {
        return this.district;
    }

    /**
     * Setter for <code>PUBLIC.ADDRESS.DISTRICT</code>.
     */
    public void setDistrict(@Nullable String district) {
        this.district = district;
    }

    /**
     * Getter for <code>PUBLIC.ADDRESS.CITY_ID</code>.
     */
    @Column(name = "CITY_ID", nullable = false)
    @NotNull
    public Long getCityId() {
        return this.cityId;
    }

    /**
     * Setter for <code>PUBLIC.ADDRESS.CITY_ID</code>.
     */
    public void setCityId(Long cityId) {
        this.cityId = cityId;
    }

    /**
     * Getter for <code>PUBLIC.ADDRESS.POSTAL_CODE</code>.
     */
    @Column(name = "POSTAL_CODE", length = 10)
    @Size(max = 10)
    @Nullable
    public String getPostalCode() {
        return this.postalCode;
    }

    /**
     * Setter for <code>PUBLIC.ADDRESS.POSTAL_CODE</code>.
     */
    public void setPostalCode(@Nullable String postalCode) {
        this.postalCode = postalCode;
    }

    /**
     * Getter for <code>PUBLIC.ADDRESS.PHONE</code>.
     */
    @Column(name = "PHONE", nullable = false, length = 20)
    @NotNull
    @Size(max = 20)
    public String getPhone() {
        return this.phone;
    }

    /**
     * Setter for <code>PUBLIC.ADDRESS.PHONE</code>.
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * Getter for <code>PUBLIC.ADDRESS.LAST_UPDATE</code>.
     */
    @Column(name = "LAST_UPDATE", nullable = false, precision = 6)
    public OffsetDateTime getLastUpdate() {
        return this.lastUpdate;
    }

    /**
     * Setter for <code>PUBLIC.ADDRESS.LAST_UPDATE</code>.
     */
    public void setLastUpdate(OffsetDateTime lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Address other = (Address) obj;
        if (this.addressId == null) {
            if (other.addressId != null)
                return false;
        }
        else if (!this.addressId.equals(other.addressId))
            return false;
        if (this.address == null) {
            if (other.address != null)
                return false;
        }
        else if (!this.address.equals(other.address))
            return false;
        if (this.address2 == null) {
            if (other.address2 != null)
                return false;
        }
        else if (!this.address2.equals(other.address2))
            return false;
        if (this.district == null) {
            if (other.district != null)
                return false;
        }
        else if (!this.district.equals(other.district))
            return false;
        if (this.cityId == null) {
            if (other.cityId != null)
                return false;
        }
        else if (!this.cityId.equals(other.cityId))
            return false;
        if (this.postalCode == null) {
            if (other.postalCode != null)
                return false;
        }
        else if (!this.postalCode.equals(other.postalCode))
            return false;
        if (this.phone == null) {
            if (other.phone != null)
                return false;
        }
        else if (!this.phone.equals(other.phone))
            return false;
        if (this.lastUpdate == null) {
            if (other.lastUpdate != null)
                return false;
        }
        else if (!this.lastUpdate.equals(other.lastUpdate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.addressId == null) ? 0 : this.addressId.hashCode());
        result = prime * result + ((this.address == null) ? 0 : this.address.hashCode());
        result = prime * result + ((this.address2 == null) ? 0 : this.address2.hashCode());
        result = prime * result + ((this.district == null) ? 0 : this.district.hashCode());
        result = prime * result + ((this.cityId == null) ? 0 : this.cityId.hashCode());
        result = prime * result + ((this.postalCode == null) ? 0 : this.postalCode.hashCode());
        result = prime * result + ((this.phone == null) ? 0 : this.phone.hashCode());
        result = prime * result + ((this.lastUpdate == null) ? 0 : this.lastUpdate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Address (");

        sb.append(addressId);
        sb.append(", ").append(address);
        sb.append(", ").append(address2);
        sb.append(", ").append(district);
        sb.append(", ").append(cityId);
        sb.append(", ").append(postalCode);
        sb.append(", ").append(phone);
        sb.append(", ").append(lastUpdate);

        sb.append(")");
        return sb.toString();
    }
}
