/*
 * This file is generated by jOOQ.
 */
package org.tayrona.sakila.data.tables.pojos;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * City details table
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "CITY",
    schema = "PUBLIC"
)
public class City implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long cityId;
    private String city;
    private Long countryId;
    private OffsetDateTime lastUpdate;

    public City() {}

    public City(City value) {
        this.cityId = value.cityId;
        this.city = value.city;
        this.countryId = value.countryId;
        this.lastUpdate = value.lastUpdate;
    }

    public City(
        Long cityId,
        String city,
        Long countryId,
        OffsetDateTime lastUpdate
    ) {
        this.cityId = cityId;
        this.city = city;
        this.countryId = countryId;
        this.lastUpdate = lastUpdate;
    }

    /**
     * Getter for <code>PUBLIC.CITY.CITY_ID</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "CITY_ID", nullable = false)
    public Long getCityId() {
        return this.cityId;
    }

    /**
     * Setter for <code>PUBLIC.CITY.CITY_ID</code>.
     */
    public void setCityId(Long cityId) {
        this.cityId = cityId;
    }

    /**
     * Getter for <code>PUBLIC.CITY.CITY</code>.
     */
    @Column(name = "CITY", nullable = false, length = 50)
    @NotNull
    @Size(max = 50)
    public String getCity() {
        return this.city;
    }

    /**
     * Setter for <code>PUBLIC.CITY.CITY</code>.
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * Getter for <code>PUBLIC.CITY.COUNTRY_ID</code>.
     */
    @Column(name = "COUNTRY_ID", nullable = false)
    @NotNull
    public Long getCountryId() {
        return this.countryId;
    }

    /**
     * Setter for <code>PUBLIC.CITY.COUNTRY_ID</code>.
     */
    public void setCountryId(Long countryId) {
        this.countryId = countryId;
    }

    /**
     * Getter for <code>PUBLIC.CITY.LAST_UPDATE</code>.
     */
    @Column(name = "LAST_UPDATE", nullable = false, precision = 6)
    public OffsetDateTime getLastUpdate() {
        return this.lastUpdate;
    }

    /**
     * Setter for <code>PUBLIC.CITY.LAST_UPDATE</code>.
     */
    public void setLastUpdate(OffsetDateTime lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final City other = (City) obj;
        if (this.cityId == null) {
            if (other.cityId != null)
                return false;
        }
        else if (!this.cityId.equals(other.cityId))
            return false;
        if (this.city == null) {
            if (other.city != null)
                return false;
        }
        else if (!this.city.equals(other.city))
            return false;
        if (this.countryId == null) {
            if (other.countryId != null)
                return false;
        }
        else if (!this.countryId.equals(other.countryId))
            return false;
        if (this.lastUpdate == null) {
            if (other.lastUpdate != null)
                return false;
        }
        else if (!this.lastUpdate.equals(other.lastUpdate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.cityId == null) ? 0 : this.cityId.hashCode());
        result = prime * result + ((this.city == null) ? 0 : this.city.hashCode());
        result = prime * result + ((this.countryId == null) ? 0 : this.countryId.hashCode());
        result = prime * result + ((this.lastUpdate == null) ? 0 : this.lastUpdate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("City (");

        sb.append(cityId);
        sb.append(", ").append(city);
        sb.append(", ").append(countryId);
        sb.append(", ").append(lastUpdate);

        sb.append(")");
        return sb.toString();
    }
}
