/*
 * This file is generated by jOOQ.
 */
package org.tayrona.sakila.data.tables.pojos;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;

import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * Film Actor cross-reference table
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "FILM_ACTOR",
    schema = "PUBLIC"
)
public class FilmActor implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long actorId;
    private Long filmId;
    private OffsetDateTime lastUpdate;

    public FilmActor() {}

    public FilmActor(FilmActor value) {
        this.actorId = value.actorId;
        this.filmId = value.filmId;
        this.lastUpdate = value.lastUpdate;
    }

    public FilmActor(
        Long actorId,
        Long filmId,
        OffsetDateTime lastUpdate
    ) {
        this.actorId = actorId;
        this.filmId = filmId;
        this.lastUpdate = lastUpdate;
    }

    /**
     * Getter for <code>PUBLIC.FILM_ACTOR.ACTOR_ID</code>.
     */
    @Column(name = "ACTOR_ID", nullable = false)
    @NotNull
    public Long getActorId() {
        return this.actorId;
    }

    /**
     * Setter for <code>PUBLIC.FILM_ACTOR.ACTOR_ID</code>.
     */
    public void setActorId(Long actorId) {
        this.actorId = actorId;
    }

    /**
     * Getter for <code>PUBLIC.FILM_ACTOR.FILM_ID</code>.
     */
    @Column(name = "FILM_ID", nullable = false)
    @NotNull
    public Long getFilmId() {
        return this.filmId;
    }

    /**
     * Setter for <code>PUBLIC.FILM_ACTOR.FILM_ID</code>.
     */
    public void setFilmId(Long filmId) {
        this.filmId = filmId;
    }

    /**
     * Getter for <code>PUBLIC.FILM_ACTOR.LAST_UPDATE</code>.
     */
    @Column(name = "LAST_UPDATE", nullable = false, precision = 6)
    public OffsetDateTime getLastUpdate() {
        return this.lastUpdate;
    }

    /**
     * Setter for <code>PUBLIC.FILM_ACTOR.LAST_UPDATE</code>.
     */
    public void setLastUpdate(OffsetDateTime lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final FilmActor other = (FilmActor) obj;
        if (this.actorId == null) {
            if (other.actorId != null)
                return false;
        }
        else if (!this.actorId.equals(other.actorId))
            return false;
        if (this.filmId == null) {
            if (other.filmId != null)
                return false;
        }
        else if (!this.filmId.equals(other.filmId))
            return false;
        if (this.lastUpdate == null) {
            if (other.lastUpdate != null)
                return false;
        }
        else if (!this.lastUpdate.equals(other.lastUpdate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.actorId == null) ? 0 : this.actorId.hashCode());
        result = prime * result + ((this.filmId == null) ? 0 : this.filmId.hashCode());
        result = prime * result + ((this.lastUpdate == null) ? 0 : this.lastUpdate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("FilmActor (");

        sb.append(actorId);
        sb.append(", ").append(filmId);
        sb.append(", ").append(lastUpdate);

        sb.append(")");
        return sb.toString();
    }
}
