/*
 * This file is generated by jOOQ.
 */
package org.tayrona.sakila.data.tables.pojos;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import jakarta.validation.constraints.NotNull;

import java.io.Serializable;
import java.time.OffsetDateTime;

import javax.annotation.Nullable;


/**
 * Store details table
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "STORE",
    schema = "PUBLIC",
    uniqueConstraints = {
        @UniqueConstraint(name = "IDX_UNIQUE_MANAGER", columnNames = { "MANAGER_STAFF_ID" })
    }
)
public class Store implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long storeId;
    private Long managerStaffId;
    private Long addressId;
    private OffsetDateTime lastUpdate;

    public Store() {}

    public Store(Store value) {
        this.storeId = value.storeId;
        this.managerStaffId = value.managerStaffId;
        this.addressId = value.addressId;
        this.lastUpdate = value.lastUpdate;
    }

    public Store(
        Long storeId,
        @Nullable Long managerStaffId,
        Long addressId,
        OffsetDateTime lastUpdate
    ) {
        this.storeId = storeId;
        this.managerStaffId = managerStaffId;
        this.addressId = addressId;
        this.lastUpdate = lastUpdate;
    }

    /**
     * Getter for <code>PUBLIC.STORE.STORE_ID</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "STORE_ID", nullable = false)
    public Long getStoreId() {
        return this.storeId;
    }

    /**
     * Setter for <code>PUBLIC.STORE.STORE_ID</code>.
     */
    public void setStoreId(Long storeId) {
        this.storeId = storeId;
    }

    /**
     * Getter for <code>PUBLIC.STORE.MANAGER_STAFF_ID</code>.
     */
    @Column(name = "MANAGER_STAFF_ID")
    @Nullable
    public Long getManagerStaffId() {
        return this.managerStaffId;
    }

    /**
     * Setter for <code>PUBLIC.STORE.MANAGER_STAFF_ID</code>.
     */
    public void setManagerStaffId(@Nullable Long managerStaffId) {
        this.managerStaffId = managerStaffId;
    }

    /**
     * Getter for <code>PUBLIC.STORE.ADDRESS_ID</code>.
     */
    @Column(name = "ADDRESS_ID", nullable = false)
    @NotNull
    public Long getAddressId() {
        return this.addressId;
    }

    /**
     * Setter for <code>PUBLIC.STORE.ADDRESS_ID</code>.
     */
    public void setAddressId(Long addressId) {
        this.addressId = addressId;
    }

    /**
     * Getter for <code>PUBLIC.STORE.LAST_UPDATE</code>.
     */
    @Column(name = "LAST_UPDATE", nullable = false, precision = 6)
    public OffsetDateTime getLastUpdate() {
        return this.lastUpdate;
    }

    /**
     * Setter for <code>PUBLIC.STORE.LAST_UPDATE</code>.
     */
    public void setLastUpdate(OffsetDateTime lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Store other = (Store) obj;
        if (this.storeId == null) {
            if (other.storeId != null)
                return false;
        }
        else if (!this.storeId.equals(other.storeId))
            return false;
        if (this.managerStaffId == null) {
            if (other.managerStaffId != null)
                return false;
        }
        else if (!this.managerStaffId.equals(other.managerStaffId))
            return false;
        if (this.addressId == null) {
            if (other.addressId != null)
                return false;
        }
        else if (!this.addressId.equals(other.addressId))
            return false;
        if (this.lastUpdate == null) {
            if (other.lastUpdate != null)
                return false;
        }
        else if (!this.lastUpdate.equals(other.lastUpdate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.storeId == null) ? 0 : this.storeId.hashCode());
        result = prime * result + ((this.managerStaffId == null) ? 0 : this.managerStaffId.hashCode());
        result = prime * result + ((this.addressId == null) ? 0 : this.addressId.hashCode());
        result = prime * result + ((this.lastUpdate == null) ? 0 : this.lastUpdate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Store (");

        sb.append(storeId);
        sb.append(", ").append(managerStaffId);
        sb.append(", ").append(addressId);
        sb.append(", ").append(lastUpdate);

        sb.append(")");
        return sb.toString();
    }
}
