/*
 * This file is generated by jOOQ.
 */
package org.tayrona.sakila.data.tables;


import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function11;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row11;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.tayrona.sakila.data.Keys;
import org.tayrona.sakila.data.Public;
import org.tayrona.sakila.data.tables.records.StaffRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;


/**
 * Staff details table
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Staff extends TableImpl<StaffRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>PUBLIC.STAFF</code>
     */
    public static final Staff STAFF = new Staff();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StaffRecord> getRecordType() {
        return StaffRecord.class;
    }

    /**
     * The column <code>PUBLIC.STAFF.STAFF_ID</code>.
     */
    public final TableField<StaffRecord, Long> STAFF_ID = createField(DSL.name("STAFF_ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>PUBLIC.STAFF.FIRST_NAME</code>.
     */
    public final TableField<StaffRecord, String> FIRST_NAME = createField(DSL.name("FIRST_NAME"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.STAFF.LAST_NAME</code>.
     */
    public final TableField<StaffRecord, String> LAST_NAME = createField(DSL.name("LAST_NAME"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.STAFF.ADDRESS_ID</code>.
     */
    public final TableField<StaffRecord, Long> ADDRESS_ID = createField(DSL.name("ADDRESS_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.STAFF.PICTURE</code>.
     */
    public final TableField<StaffRecord, byte[]> PICTURE = createField(DSL.name("PICTURE"), SQLDataType.BLOB.defaultValue(DSL.field("NULL", SQLDataType.BLOB)), this, "");

    /**
     * The column <code>PUBLIC.STAFF.EMAIL</code>.
     */
    public final TableField<StaffRecord, String> EMAIL = createField(DSL.name("EMAIL"), SQLDataType.VARCHAR(50).defaultValue(DSL.field("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>PUBLIC.STAFF.STORE_ID</code>.
     */
    public final TableField<StaffRecord, Long> STORE_ID = createField(DSL.name("STORE_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.STAFF.ACTIVE</code>.
     */
    public final TableField<StaffRecord, Boolean> ACTIVE = createField(DSL.name("ACTIVE"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field("TRUE", SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>PUBLIC.STAFF.USERNAME</code>.
     */
    public final TableField<StaffRecord, String> USERNAME = createField(DSL.name("USERNAME"), SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.STAFF.PASSWORD</code>.
     */
    public final TableField<StaffRecord, byte[]> PASSWORD = createField(DSL.name("PASSWORD"), SQLDataType.BINARY(40).defaultValue(DSL.field("NULL", SQLDataType.BINARY)), this, "");

    /**
     * The column <code>PUBLIC.STAFF.LAST_UPDATE</code>.
     */
    public final TableField<StaffRecord, LocalDateTime> LAST_UPDATE = createField(DSL.name("LAST_UPDATE"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    private Staff(Name alias, Table<StaffRecord> aliased) {
        this(alias, aliased, null);
    }

    private Staff(Name alias, Table<StaffRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("Staff details table"), TableOptions.table());
    }

    /**
     * Create an aliased <code>PUBLIC.STAFF</code> table reference
     */
    public Staff(String alias) {
        this(DSL.name(alias), STAFF);
    }

    /**
     * Create an aliased <code>PUBLIC.STAFF</code> table reference
     */
    public Staff(Name alias) {
        this(alias, STAFF);
    }

    /**
     * Create a <code>PUBLIC.STAFF</code> table reference
     */
    public Staff() {
        this(DSL.name("STAFF"), null);
    }

    public <O extends Record> Staff(Table<O> child, ForeignKey<O, StaffRecord> key) {
        super(child, key, STAFF);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<StaffRecord, Long> getIdentity() {
        return (Identity<StaffRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<StaffRecord> getPrimaryKey() {
        return Keys.PK_STAFF;
    }

    @Override
    public List<ForeignKey<StaffRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_STAFF_ADDRESS, Keys.FK_STAFF_STORE);
    }

    private transient Address _address;
    private transient Store _store;

    /**
     * Get the implicit join path to the <code>PUBLIC.ADDRESS</code> table.
     */
    public Address address() {
        if (_address == null)
            _address = new Address(this, Keys.FK_STAFF_ADDRESS);

        return _address;
    }

    /**
     * Get the implicit join path to the <code>PUBLIC.STORE</code> table.
     */
    public Store store() {
        if (_store == null)
            _store = new Store(this, Keys.FK_STAFF_STORE);

        return _store;
    }

    @Override
    public Staff as(String alias) {
        return new Staff(DSL.name(alias), this);
    }

    @Override
    public Staff as(Name alias) {
        return new Staff(alias, this);
    }

    @Override
    public Staff as(Table<?> alias) {
        return new Staff(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Staff rename(String name) {
        return new Staff(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Staff rename(Name name) {
        return new Staff(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Staff rename(Table<?> name) {
        return new Staff(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row11 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row11<Long, String, String, Long, byte[], String, Long, Boolean, String, byte[], LocalDateTime> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function11<? super Long, ? super String, ? super String, ? super Long, ? super byte[], ? super String, ? super Long, ? super Boolean, ? super String, ? super byte[], ? super LocalDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function11<? super Long, ? super String, ? super String, ? super Long, ? super byte[], ? super String, ? super Long, ? super Boolean, ? super String, ? super byte[], ? super LocalDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
