/*
 * This file is generated by jOOQ.
 */
package org.tayrona.sakila.data.tables.records;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;
import org.tayrona.sakila.data.tables.Actor;

import java.time.OffsetDateTime;


/**
 * Actor details table
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "ACTOR",
    schema = "PUBLIC"
)
public class ActorRecord extends UpdatableRecordImpl<ActorRecord> implements Record4<Long, String, String, OffsetDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>PUBLIC.ACTOR.ACTOR_ID</code>.
     */
    public void setActorId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.ACTOR.ACTOR_ID</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ACTOR_ID", nullable = false)
    public Long getActorId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.ACTOR.FIRST_NAME</code>.
     */
    public void setFirstName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.ACTOR.FIRST_NAME</code>.
     */
    @Column(name = "FIRST_NAME", nullable = false, length = 45)
    @NotNull
    @Size(max = 45)
    public String getFirstName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.ACTOR.LAST_NAME</code>.
     */
    public void setLastName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.ACTOR.LAST_NAME</code>.
     */
    @Column(name = "LAST_NAME", nullable = false, length = 45)
    @NotNull
    @Size(max = 45)
    public String getLastName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.ACTOR.LAST_UPDATE</code>.
     */
    public void setLastUpdate(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.ACTOR.LAST_UPDATE</code>.
     */
    @Column(name = "LAST_UPDATE", nullable = false, precision = 6)
    public OffsetDateTime getLastUpdate() {
        return (OffsetDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, String, String, OffsetDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, String, String, OffsetDateTime> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Actor.ACTOR.ACTOR_ID;
    }

    @Override
    public Field<String> field2() {
        return Actor.ACTOR.FIRST_NAME;
    }

    @Override
    public Field<String> field3() {
        return Actor.ACTOR.LAST_NAME;
    }

    @Override
    public Field<OffsetDateTime> field4() {
        return Actor.ACTOR.LAST_UPDATE;
    }

    @Override
    public Long component1() {
        return getActorId();
    }

    @Override
    public String component2() {
        return getFirstName();
    }

    @Override
    public String component3() {
        return getLastName();
    }

    @Override
    public OffsetDateTime component4() {
        return getLastUpdate();
    }

    @Override
    public Long value1() {
        return getActorId();
    }

    @Override
    public String value2() {
        return getFirstName();
    }

    @Override
    public String value3() {
        return getLastName();
    }

    @Override
    public OffsetDateTime value4() {
        return getLastUpdate();
    }

    @Override
    public ActorRecord value1(Long value) {
        setActorId(value);
        return this;
    }

    @Override
    public ActorRecord value2(String value) {
        setFirstName(value);
        return this;
    }

    @Override
    public ActorRecord value3(String value) {
        setLastName(value);
        return this;
    }

    @Override
    public ActorRecord value4(OffsetDateTime value) {
        setLastUpdate(value);
        return this;
    }

    @Override
    public ActorRecord values(Long value1, String value2, String value3, OffsetDateTime value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ActorRecord
     */
    public ActorRecord() {
        super(Actor.ACTOR);
    }

    /**
     * Create a detached, initialised ActorRecord
     */
    public ActorRecord(Long actorId, String firstName, String lastName, OffsetDateTime lastUpdate) {
        super(Actor.ACTOR);

        setActorId(actorId);
        setFirstName(firstName);
        setLastName(lastName);
        setLastUpdate(lastUpdate);
    }

    /**
     * Create a detached, initialised ActorRecord
     */
    public ActorRecord(org.tayrona.sakila.data.tables.pojos.Actor value) {
        super(Actor.ACTOR);

        if (value != null) {
            setActorId(value.getActorId());
            setFirstName(value.getFirstName());
            setLastName(value.getLastName());
            setLastUpdate(value.getLastUpdate());
        }
    }
}
