/*
 * This file is generated by jOOQ.
 */
package org.tayrona.sakila.data.tables.records;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.time.OffsetDateTime;

import javax.annotation.Nullable;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;
import org.tayrona.sakila.data.tables.Customer;


/**
 * Customer details table
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "CUSTOMER",
    schema = "PUBLIC",
    indexes = {
        @Index(name = "IDX_LAST_NAME", columnList = "LAST_NAME ASC")
    }
)
public class CustomerRecord extends UpdatableRecordImpl<CustomerRecord> implements Record9<Long, Long, String, String, String, Long, Boolean, OffsetDateTime, OffsetDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>PUBLIC.CUSTOMER.CUSTOMER_ID</code>.
     */
    public void setCustomerId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.CUSTOMER.CUSTOMER_ID</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "CUSTOMER_ID", nullable = false)
    public Long getCustomerId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.CUSTOMER.STORE_ID</code>.
     */
    public void setStoreId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.CUSTOMER.STORE_ID</code>.
     */
    @Column(name = "STORE_ID", nullable = false)
    @NotNull
    public Long getStoreId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>PUBLIC.CUSTOMER.FIRST_NAME</code>.
     */
    public void setFirstName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.CUSTOMER.FIRST_NAME</code>.
     */
    @Column(name = "FIRST_NAME", nullable = false, length = 45)
    @NotNull
    @Size(max = 45)
    public String getFirstName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.CUSTOMER.LAST_NAME</code>.
     */
    public void setLastName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.CUSTOMER.LAST_NAME</code>.
     */
    @Column(name = "LAST_NAME", nullable = false, length = 45)
    @NotNull
    @Size(max = 45)
    public String getLastName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>PUBLIC.CUSTOMER.EMAIL</code>.
     */
    public void setEmail(@Nullable String value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.CUSTOMER.EMAIL</code>.
     */
    @Column(name = "EMAIL", length = 50)
    @Size(max = 50)
    @Nullable
    public String getEmail() {
        return (String) get(4);
    }

    /**
     * Setter for <code>PUBLIC.CUSTOMER.ADDRESS_ID</code>.
     */
    public void setAddressId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>PUBLIC.CUSTOMER.ADDRESS_ID</code>.
     */
    @Column(name = "ADDRESS_ID", nullable = false)
    @NotNull
    public Long getAddressId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>PUBLIC.CUSTOMER.ACTIVE</code>.
     */
    public void setActive(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>PUBLIC.CUSTOMER.ACTIVE</code>.
     */
    @Column(name = "ACTIVE", nullable = false)
    public Boolean getActive() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>PUBLIC.CUSTOMER.CREATE_DATE</code>.
     */
    public void setCreateDate(OffsetDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>PUBLIC.CUSTOMER.CREATE_DATE</code>.
     */
    @Column(name = "CREATE_DATE", nullable = false, precision = 6)
    public OffsetDateTime getCreateDate() {
        return (OffsetDateTime) get(7);
    }

    /**
     * Setter for <code>PUBLIC.CUSTOMER.LAST_UPDATE</code>.
     */
    public void setLastUpdate(OffsetDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>PUBLIC.CUSTOMER.LAST_UPDATE</code>.
     */
    @Column(name = "LAST_UPDATE", nullable = false, precision = 6)
    public OffsetDateTime getLastUpdate() {
        return (OffsetDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, Long, String, String, String, Long, Boolean, OffsetDateTime, OffsetDateTime> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Long, Long, String, String, String, Long, Boolean, OffsetDateTime, OffsetDateTime> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Customer.CUSTOMER.CUSTOMER_ID;
    }

    @Override
    public Field<Long> field2() {
        return Customer.CUSTOMER.STORE_ID;
    }

    @Override
    public Field<String> field3() {
        return Customer.CUSTOMER.FIRST_NAME;
    }

    @Override
    public Field<String> field4() {
        return Customer.CUSTOMER.LAST_NAME;
    }

    @Override
    public Field<String> field5() {
        return Customer.CUSTOMER.EMAIL;
    }

    @Override
    public Field<Long> field6() {
        return Customer.CUSTOMER.ADDRESS_ID;
    }

    @Override
    public Field<Boolean> field7() {
        return Customer.CUSTOMER.ACTIVE;
    }

    @Override
    public Field<OffsetDateTime> field8() {
        return Customer.CUSTOMER.CREATE_DATE;
    }

    @Override
    public Field<OffsetDateTime> field9() {
        return Customer.CUSTOMER.LAST_UPDATE;
    }

    @Override
    public Long component1() {
        return getCustomerId();
    }

    @Override
    public Long component2() {
        return getStoreId();
    }

    @Override
    public String component3() {
        return getFirstName();
    }

    @Override
    public String component4() {
        return getLastName();
    }

    @Override
    @Nullable
    public String component5() {
        return getEmail();
    }

    @Override
    public Long component6() {
        return getAddressId();
    }

    @Override
    public Boolean component7() {
        return getActive();
    }

    @Override
    public OffsetDateTime component8() {
        return getCreateDate();
    }

    @Override
    public OffsetDateTime component9() {
        return getLastUpdate();
    }

    @Override
    public Long value1() {
        return getCustomerId();
    }

    @Override
    public Long value2() {
        return getStoreId();
    }

    @Override
    public String value3() {
        return getFirstName();
    }

    @Override
    public String value4() {
        return getLastName();
    }

    @Override
    @Nullable
    public String value5() {
        return getEmail();
    }

    @Override
    public Long value6() {
        return getAddressId();
    }

    @Override
    public Boolean value7() {
        return getActive();
    }

    @Override
    public OffsetDateTime value8() {
        return getCreateDate();
    }

    @Override
    public OffsetDateTime value9() {
        return getLastUpdate();
    }

    @Override
    public CustomerRecord value1(Long value) {
        setCustomerId(value);
        return this;
    }

    @Override
    public CustomerRecord value2(Long value) {
        setStoreId(value);
        return this;
    }

    @Override
    public CustomerRecord value3(String value) {
        setFirstName(value);
        return this;
    }

    @Override
    public CustomerRecord value4(String value) {
        setLastName(value);
        return this;
    }

    @Override
    public CustomerRecord value5(@Nullable String value) {
        setEmail(value);
        return this;
    }

    @Override
    public CustomerRecord value6(Long value) {
        setAddressId(value);
        return this;
    }

    @Override
    public CustomerRecord value7(Boolean value) {
        setActive(value);
        return this;
    }

    @Override
    public CustomerRecord value8(OffsetDateTime value) {
        setCreateDate(value);
        return this;
    }

    @Override
    public CustomerRecord value9(OffsetDateTime value) {
        setLastUpdate(value);
        return this;
    }

    @Override
    public CustomerRecord values(Long value1, Long value2, String value3, String value4, @Nullable String value5, Long value6, Boolean value7, OffsetDateTime value8, OffsetDateTime value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CustomerRecord
     */
    public CustomerRecord() {
        super(Customer.CUSTOMER);
    }

    /**
     * Create a detached, initialised CustomerRecord
     */
    public CustomerRecord(Long customerId, Long storeId, String firstName, String lastName, @Nullable String email, Long addressId, Boolean active, OffsetDateTime createDate, OffsetDateTime lastUpdate) {
        super(Customer.CUSTOMER);

        setCustomerId(customerId);
        setStoreId(storeId);
        setFirstName(firstName);
        setLastName(lastName);
        setEmail(email);
        setAddressId(addressId);
        setActive(active);
        setCreateDate(createDate);
        setLastUpdate(lastUpdate);
    }

    /**
     * Create a detached, initialised CustomerRecord
     */
    public CustomerRecord(org.tayrona.sakila.data.tables.pojos.Customer value) {
        super(Customer.CUSTOMER);

        if (value != null) {
            setCustomerId(value.getCustomerId());
            setStoreId(value.getStoreId());
            setFirstName(value.getFirstName());
            setLastName(value.getLastName());
            setEmail(value.getEmail());
            setAddressId(value.getAddressId());
            setActive(value.getActive());
            setCreateDate(value.getCreateDate());
            setLastUpdate(value.getLastUpdate());
        }
    }
}
