/*
 * This file is generated by jOOQ.
 */
package org.tayrona.sakila.data.tables.records;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.math.BigDecimal;
import java.time.OffsetDateTime;

import javax.annotation.Nullable;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;
import org.tayrona.sakila.data.enums.MpaaRating;
import org.tayrona.sakila.data.tables.Film;


/**
 * Film details table
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "FILM",
    schema = "PUBLIC",
    indexes = {
        @Index(name = "IDX_BARCODE", unique = true, columnList = "BARCODE ASC"),
        @Index(name = "IDX_REVERSE_BARCODE", unique = true, columnList = "REVERSE_BARCODE ASC"),
        @Index(name = "IDX_TITLE", unique = true, columnList = "TITLE ASC")
    }
)
public class FilmRecord extends UpdatableRecordImpl<FilmRecord> implements Record14<Long, String, String, Short, Long, Long, Byte, BigDecimal, Short, BigDecimal, String, String, MpaaRating, OffsetDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>PUBLIC.FILM.FILM_ID</code>.
     */
    public void setFilmId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.FILM.FILM_ID</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "FILM_ID", nullable = false)
    public Long getFilmId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.FILM.TITLE</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.FILM.TITLE</code>.
     */
    @Column(name = "TITLE", nullable = false, length = 255)
    @NotNull
    @Size(max = 255)
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.FILM.DESCRIPTION</code>.
     */
    public void setDescription(@Nullable String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.FILM.DESCRIPTION</code>.
     */
    @Column(name = "DESCRIPTION", length = 1000000000)
    @Size(max = 1000000000)
    @Nullable
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.FILM.RELEASE_YEAR</code>. YearValue a small int
     * between 1900 and 2155
     */
    public void setReleaseYear(@Nullable Short value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.FILM.RELEASE_YEAR</code>. YearValue a small int
     * between 1900 and 2155
     */
    @Column(name = "RELEASE_YEAR")
    @Nullable
    public Short getReleaseYear() {
        return (Short) get(3);
    }

    /**
     * Setter for <code>PUBLIC.FILM.LANGUAGE_ID</code>.
     */
    public void setLanguageId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.FILM.LANGUAGE_ID</code>.
     */
    @Column(name = "LANGUAGE_ID", nullable = false)
    @NotNull
    public Long getLanguageId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>PUBLIC.FILM.ORIGINAL_LANGUAGE_ID</code>.
     */
    public void setOriginalLanguageId(@Nullable Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>PUBLIC.FILM.ORIGINAL_LANGUAGE_ID</code>.
     */
    @Column(name = "ORIGINAL_LANGUAGE_ID")
    @Nullable
    public Long getOriginalLanguageId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>PUBLIC.FILM.RENTAL_DURATION</code>.
     */
    public void setRentalDuration(Byte value) {
        set(6, value);
    }

    /**
     * Getter for <code>PUBLIC.FILM.RENTAL_DURATION</code>.
     */
    @Column(name = "RENTAL_DURATION", nullable = false)
    public Byte getRentalDuration() {
        return (Byte) get(6);
    }

    /**
     * Setter for <code>PUBLIC.FILM.RENTAL_RATE</code>.
     */
    public void setRentalRate(BigDecimal value) {
        set(7, value);
    }

    /**
     * Getter for <code>PUBLIC.FILM.RENTAL_RATE</code>.
     */
    @Column(name = "RENTAL_RATE", nullable = false, precision = 4, scale = 2)
    public BigDecimal getRentalRate() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>PUBLIC.FILM.LENGTH</code>.
     */
    public void setLength(@Nullable Short value) {
        set(8, value);
    }

    /**
     * Getter for <code>PUBLIC.FILM.LENGTH</code>.
     */
    @Column(name = "LENGTH")
    @Nullable
    public Short getLength() {
        return (Short) get(8);
    }

    /**
     * Setter for <code>PUBLIC.FILM.REPLACEMENT_COST</code>.
     */
    public void setReplacementCost(BigDecimal value) {
        set(9, value);
    }

    /**
     * Getter for <code>PUBLIC.FILM.REPLACEMENT_COST</code>.
     */
    @Column(name = "REPLACEMENT_COST", nullable = false, precision = 5, scale = 2)
    public BigDecimal getReplacementCost() {
        return (BigDecimal) get(9);
    }

    /**
     * Setter for <code>PUBLIC.FILM.BARCODE</code>. UPC is barcode of length 12
     * characters
     */
    public void setBarcode(@Nullable String value) {
        set(10, value);
    }

    /**
     * Getter for <code>PUBLIC.FILM.BARCODE</code>. UPC is barcode of length 12
     * characters
     */
    @Column(name = "BARCODE", length = 12)
    @Size(max = 12)
    @Nullable
    public String getBarcode() {
        return (String) get(10);
    }

    /**
     * Setter for <code>PUBLIC.FILM.REVERSE_BARCODE</code>. UPC is barcode of
     * length 12 characters
     */
    public void setReverseBarcode(@Nullable String value) {
        set(11, value);
    }

    /**
     * Getter for <code>PUBLIC.FILM.REVERSE_BARCODE</code>. UPC is barcode of
     * length 12 characters
     */
    @Column(name = "REVERSE_BARCODE", length = 12)
    @Size(max = 12)
    @Nullable
    public String getReverseBarcode() {
        return (String) get(11);
    }

    /**
     * Setter for <code>PUBLIC.FILM.RATING</code>. MPAA Rating ENUM
     * (G,PG,PG-13,R,NC-17)
     */
    public void setRating(@Nullable MpaaRating value) {
        set(12, value);
    }

    /**
     * Getter for <code>PUBLIC.FILM.RATING</code>. MPAA Rating ENUM
     * (G,PG,PG-13,R,NC-17)
     */
    @Column(name = "RATING")
    @Nullable
    public MpaaRating getRating() {
        return (MpaaRating) get(12);
    }

    /**
     * Setter for <code>PUBLIC.FILM.LAST_UPDATE</code>.
     */
    public void setLastUpdate(OffsetDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>PUBLIC.FILM.LAST_UPDATE</code>.
     */
    @Column(name = "LAST_UPDATE", nullable = false, precision = 6)
    public OffsetDateTime getLastUpdate() {
        return (OffsetDateTime) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row14<Long, String, String, Short, Long, Long, Byte, BigDecimal, Short, BigDecimal, String, String, MpaaRating, OffsetDateTime> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    @Override
    public Row14<Long, String, String, Short, Long, Long, Byte, BigDecimal, Short, BigDecimal, String, String, MpaaRating, OffsetDateTime> valuesRow() {
        return (Row14) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Film.FILM.FILM_ID;
    }

    @Override
    public Field<String> field2() {
        return Film.FILM.TITLE;
    }

    @Override
    public Field<String> field3() {
        return Film.FILM.DESCRIPTION;
    }

    @Override
    public Field<Short> field4() {
        return Film.FILM.RELEASE_YEAR;
    }

    @Override
    public Field<Long> field5() {
        return Film.FILM.LANGUAGE_ID;
    }

    @Override
    public Field<Long> field6() {
        return Film.FILM.ORIGINAL_LANGUAGE_ID;
    }

    @Override
    public Field<Byte> field7() {
        return Film.FILM.RENTAL_DURATION;
    }

    @Override
    public Field<BigDecimal> field8() {
        return Film.FILM.RENTAL_RATE;
    }

    @Override
    public Field<Short> field9() {
        return Film.FILM.LENGTH;
    }

    @Override
    public Field<BigDecimal> field10() {
        return Film.FILM.REPLACEMENT_COST;
    }

    @Override
    public Field<String> field11() {
        return Film.FILM.BARCODE;
    }

    @Override
    public Field<String> field12() {
        return Film.FILM.REVERSE_BARCODE;
    }

    @Override
    public Field<MpaaRating> field13() {
        return Film.FILM.RATING;
    }

    @Override
    public Field<OffsetDateTime> field14() {
        return Film.FILM.LAST_UPDATE;
    }

    @Override
    public Long component1() {
        return getFilmId();
    }

    @Override
    public String component2() {
        return getTitle();
    }

    @Override
    @Nullable
    public String component3() {
        return getDescription();
    }

    @Override
    @Nullable
    public Short component4() {
        return getReleaseYear();
    }

    @Override
    public Long component5() {
        return getLanguageId();
    }

    @Override
    @Nullable
    public Long component6() {
        return getOriginalLanguageId();
    }

    @Override
    public Byte component7() {
        return getRentalDuration();
    }

    @Override
    public BigDecimal component8() {
        return getRentalRate();
    }

    @Override
    @Nullable
    public Short component9() {
        return getLength();
    }

    @Override
    public BigDecimal component10() {
        return getReplacementCost();
    }

    @Override
    @Nullable
    public String component11() {
        return getBarcode();
    }

    @Override
    @Nullable
    public String component12() {
        return getReverseBarcode();
    }

    @Override
    @Nullable
    public MpaaRating component13() {
        return getRating();
    }

    @Override
    public OffsetDateTime component14() {
        return getLastUpdate();
    }

    @Override
    public Long value1() {
        return getFilmId();
    }

    @Override
    public String value2() {
        return getTitle();
    }

    @Override
    @Nullable
    public String value3() {
        return getDescription();
    }

    @Override
    @Nullable
    public Short value4() {
        return getReleaseYear();
    }

    @Override
    public Long value5() {
        return getLanguageId();
    }

    @Override
    @Nullable
    public Long value6() {
        return getOriginalLanguageId();
    }

    @Override
    public Byte value7() {
        return getRentalDuration();
    }

    @Override
    public BigDecimal value8() {
        return getRentalRate();
    }

    @Override
    @Nullable
    public Short value9() {
        return getLength();
    }

    @Override
    public BigDecimal value10() {
        return getReplacementCost();
    }

    @Override
    @Nullable
    public String value11() {
        return getBarcode();
    }

    @Override
    @Nullable
    public String value12() {
        return getReverseBarcode();
    }

    @Override
    @Nullable
    public MpaaRating value13() {
        return getRating();
    }

    @Override
    public OffsetDateTime value14() {
        return getLastUpdate();
    }

    @Override
    public FilmRecord value1(Long value) {
        setFilmId(value);
        return this;
    }

    @Override
    public FilmRecord value2(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public FilmRecord value3(@Nullable String value) {
        setDescription(value);
        return this;
    }

    @Override
    public FilmRecord value4(@Nullable Short value) {
        setReleaseYear(value);
        return this;
    }

    @Override
    public FilmRecord value5(Long value) {
        setLanguageId(value);
        return this;
    }

    @Override
    public FilmRecord value6(@Nullable Long value) {
        setOriginalLanguageId(value);
        return this;
    }

    @Override
    public FilmRecord value7(Byte value) {
        setRentalDuration(value);
        return this;
    }

    @Override
    public FilmRecord value8(BigDecimal value) {
        setRentalRate(value);
        return this;
    }

    @Override
    public FilmRecord value9(@Nullable Short value) {
        setLength(value);
        return this;
    }

    @Override
    public FilmRecord value10(BigDecimal value) {
        setReplacementCost(value);
        return this;
    }

    @Override
    public FilmRecord value11(@Nullable String value) {
        setBarcode(value);
        return this;
    }

    @Override
    public FilmRecord value12(@Nullable String value) {
        setReverseBarcode(value);
        return this;
    }

    @Override
    public FilmRecord value13(@Nullable MpaaRating value) {
        setRating(value);
        return this;
    }

    @Override
    public FilmRecord value14(OffsetDateTime value) {
        setLastUpdate(value);
        return this;
    }

    @Override
    public FilmRecord values(Long value1, String value2, @Nullable String value3, @Nullable Short value4, Long value5, @Nullable Long value6, Byte value7, BigDecimal value8, @Nullable Short value9, BigDecimal value10, @Nullable String value11, @Nullable String value12, @Nullable MpaaRating value13, OffsetDateTime value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FilmRecord
     */
    public FilmRecord() {
        super(Film.FILM);
    }

    /**
     * Create a detached, initialised FilmRecord
     */
    public FilmRecord(Long filmId, String title, @Nullable String description, @Nullable Short releaseYear, Long languageId, @Nullable Long originalLanguageId, Byte rentalDuration, BigDecimal rentalRate, @Nullable Short length, BigDecimal replacementCost, @Nullable String barcode, @Nullable String reverseBarcode, @Nullable MpaaRating rating, OffsetDateTime lastUpdate) {
        super(Film.FILM);

        setFilmId(filmId);
        setTitle(title);
        setDescription(description);
        setReleaseYear(releaseYear);
        setLanguageId(languageId);
        setOriginalLanguageId(originalLanguageId);
        setRentalDuration(rentalDuration);
        setRentalRate(rentalRate);
        setLength(length);
        setReplacementCost(replacementCost);
        setBarcode(barcode);
        setReverseBarcode(reverseBarcode);
        setRating(rating);
        setLastUpdate(lastUpdate);
    }

    /**
     * Create a detached, initialised FilmRecord
     */
    public FilmRecord(org.tayrona.sakila.data.tables.pojos.Film value) {
        super(Film.FILM);

        if (value != null) {
            setFilmId(value.getFilmId());
            setTitle(value.getTitle());
            setDescription(value.getDescription());
            setReleaseYear(value.getReleaseYear());
            setLanguageId(value.getLanguageId());
            setOriginalLanguageId(value.getOriginalLanguageId());
            setRentalDuration(value.getRentalDuration());
            setRentalRate(value.getRentalRate());
            setLength(value.getLength());
            setReplacementCost(value.getReplacementCost());
            setBarcode(value.getBarcode());
            setReverseBarcode(value.getReverseBarcode());
            setRating(value.getRating());
            setLastUpdate(value.getLastUpdate());
        }
    }
}
