/*
 * This file is generated by jOOQ.
 */
package org.tayrona.sakila.data.tables.records;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.tayrona.sakila.data.tables.FilmText;

import javax.annotation.Nullable;


/**
 * Film title and description table for fulltext search
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "FILM_TEXT",
    schema = "PUBLIC",
    indexes = {
        @Index(name = "IDX_TITLE_DESCRIPTION", unique = true, columnList = "TITLE ASC, DESCRIPTION ASC")
    }
)
public class FilmTextRecord extends UpdatableRecordImpl<FilmTextRecord> implements Record3<Long, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>PUBLIC.FILM_TEXT.FILM_ID</code>.
     */
    public void setFilmId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.FILM_TEXT.FILM_ID</code>.
     */
    @Id
    @Column(name = "FILM_ID", nullable = false)
    @NotNull
    public Long getFilmId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.FILM_TEXT.TITLE</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.FILM_TEXT.TITLE</code>.
     */
    @Column(name = "TITLE", nullable = false, length = 255)
    @NotNull
    @Size(max = 255)
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.FILM_TEXT.DESCRIPTION</code>.
     */
    public void setDescription(@Nullable String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.FILM_TEXT.DESCRIPTION</code>.
     */
    @Column(name = "DESCRIPTION", length = 1000000000)
    @Size(max = 1000000000)
    @Nullable
    public String getDescription() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Long, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return FilmText.FILM_TEXT.FILM_ID;
    }

    @Override
    public Field<String> field2() {
        return FilmText.FILM_TEXT.TITLE;
    }

    @Override
    public Field<String> field3() {
        return FilmText.FILM_TEXT.DESCRIPTION;
    }

    @Override
    public Long component1() {
        return getFilmId();
    }

    @Override
    public String component2() {
        return getTitle();
    }

    @Override
    @Nullable
    public String component3() {
        return getDescription();
    }

    @Override
    public Long value1() {
        return getFilmId();
    }

    @Override
    public String value2() {
        return getTitle();
    }

    @Override
    @Nullable
    public String value3() {
        return getDescription();
    }

    @Override
    public FilmTextRecord value1(Long value) {
        setFilmId(value);
        return this;
    }

    @Override
    public FilmTextRecord value2(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public FilmTextRecord value3(@Nullable String value) {
        setDescription(value);
        return this;
    }

    @Override
    public FilmTextRecord values(Long value1, String value2, @Nullable String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FilmTextRecord
     */
    public FilmTextRecord() {
        super(FilmText.FILM_TEXT);
    }

    /**
     * Create a detached, initialised FilmTextRecord
     */
    public FilmTextRecord(Long filmId, String title, @Nullable String description) {
        super(FilmText.FILM_TEXT);

        setFilmId(filmId);
        setTitle(title);
        setDescription(description);
    }

    /**
     * Create a detached, initialised FilmTextRecord
     */
    public FilmTextRecord(org.tayrona.sakila.data.tables.pojos.FilmText value) {
        super(FilmText.FILM_TEXT);

        if (value != null) {
            setFilmId(value.getFilmId());
            setTitle(value.getTitle());
            setDescription(value.getDescription());
        }
    }
}
