/*
 * This file is generated by jOOQ.
 */
package org.tayrona.sakila.data.tables.records;


import java.math.BigDecimal;
import java.time.OffsetDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;
import org.tayrona.sakila.data.enums.MpaaRating;
import org.tayrona.sakila.data.tables.Film;


/**
 * Film details table
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FilmRecord extends UpdatableRecordImpl<FilmRecord> implements Record15<Long, String, String, Short, Long, Long, Byte, BigDecimal, Short, BigDecimal, String, String, MpaaRating, String[], OffsetDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>PUBLIC.FILM.FILM_ID</code>.
     */
    public void setFilmId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.FILM.FILM_ID</code>.
     */
    public Long getFilmId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.FILM.TITLE</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.FILM.TITLE</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.FILM.DESCRIPTION</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.FILM.DESCRIPTION</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.FILM.RELEASE_YEAR</code>. YearValue a small int
     * between 1900 and 2155
     */
    public void setReleaseYear(Short value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.FILM.RELEASE_YEAR</code>. YearValue a small int
     * between 1900 and 2155
     */
    public Short getReleaseYear() {
        return (Short) get(3);
    }

    /**
     * Setter for <code>PUBLIC.FILM.LANGUAGE_ID</code>.
     */
    public void setLanguageId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.FILM.LANGUAGE_ID</code>.
     */
    public Long getLanguageId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>PUBLIC.FILM.ORIGINAL_LANGUAGE_ID</code>.
     */
    public void setOriginalLanguageId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>PUBLIC.FILM.ORIGINAL_LANGUAGE_ID</code>.
     */
    public Long getOriginalLanguageId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>PUBLIC.FILM.RENTAL_DURATION</code>.
     */
    public void setRentalDuration(Byte value) {
        set(6, value);
    }

    /**
     * Getter for <code>PUBLIC.FILM.RENTAL_DURATION</code>.
     */
    public Byte getRentalDuration() {
        return (Byte) get(6);
    }

    /**
     * Setter for <code>PUBLIC.FILM.RENTAL_RATE</code>.
     */
    public void setRentalRate(BigDecimal value) {
        set(7, value);
    }

    /**
     * Getter for <code>PUBLIC.FILM.RENTAL_RATE</code>.
     */
    public BigDecimal getRentalRate() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>PUBLIC.FILM.LENGTH</code>.
     */
    public void setLength(Short value) {
        set(8, value);
    }

    /**
     * Getter for <code>PUBLIC.FILM.LENGTH</code>.
     */
    public Short getLength() {
        return (Short) get(8);
    }

    /**
     * Setter for <code>PUBLIC.FILM.REPLACEMENT_COST</code>.
     */
    public void setReplacementCost(BigDecimal value) {
        set(9, value);
    }

    /**
     * Getter for <code>PUBLIC.FILM.REPLACEMENT_COST</code>.
     */
    public BigDecimal getReplacementCost() {
        return (BigDecimal) get(9);
    }

    /**
     * Setter for <code>PUBLIC.FILM.BARCODE</code>.
     */
    public void setBarcode(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>PUBLIC.FILM.BARCODE</code>.
     */
    public String getBarcode() {
        return (String) get(10);
    }

    /**
     * Setter for <code>PUBLIC.FILM.REVERSE_BARCODE</code>.
     */
    public void setReverseBarcode(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>PUBLIC.FILM.REVERSE_BARCODE</code>.
     */
    public String getReverseBarcode() {
        return (String) get(11);
    }

    /**
     * Setter for <code>PUBLIC.FILM.RATING</code>. MPAA Rating ENUM
     * (G,PG,PG-13,R,NC-17)
     */
    public void setRating(MpaaRating value) {
        set(12, value);
    }

    /**
     * Getter for <code>PUBLIC.FILM.RATING</code>. MPAA Rating ENUM
     * (G,PG,PG-13,R,NC-17)
     */
    public MpaaRating getRating() {
        return (MpaaRating) get(12);
    }

    /**
     * Setter for <code>PUBLIC.FILM.SPECIAL_FEATURES</code>. Special features
     * array (Trailers, Commentaries, Deleted Scenes, Behind the Scenes)
     */
    public void setSpecialFeatures(String[] value) {
        set(13, value);
    }

    /**
     * Getter for <code>PUBLIC.FILM.SPECIAL_FEATURES</code>. Special features
     * array (Trailers, Commentaries, Deleted Scenes, Behind the Scenes)
     */
    public String[] getSpecialFeatures() {
        return (String[]) get(13);
    }

    /**
     * Setter for <code>PUBLIC.FILM.LAST_UPDATE</code>.
     */
    public void setLastUpdate(OffsetDateTime value) {
        set(14, value);
    }

    /**
     * Getter for <code>PUBLIC.FILM.LAST_UPDATE</code>.
     */
    public OffsetDateTime getLastUpdate() {
        return (OffsetDateTime) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row15<Long, String, String, Short, Long, Long, Byte, BigDecimal, Short, BigDecimal, String, String, MpaaRating, String[], OffsetDateTime> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    @Override
    public Row15<Long, String, String, Short, Long, Long, Byte, BigDecimal, Short, BigDecimal, String, String, MpaaRating, String[], OffsetDateTime> valuesRow() {
        return (Row15) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Film.FILM.FILM_ID;
    }

    @Override
    public Field<String> field2() {
        return Film.FILM.TITLE;
    }

    @Override
    public Field<String> field3() {
        return Film.FILM.DESCRIPTION;
    }

    @Override
    public Field<Short> field4() {
        return Film.FILM.RELEASE_YEAR;
    }

    @Override
    public Field<Long> field5() {
        return Film.FILM.LANGUAGE_ID;
    }

    @Override
    public Field<Long> field6() {
        return Film.FILM.ORIGINAL_LANGUAGE_ID;
    }

    @Override
    public Field<Byte> field7() {
        return Film.FILM.RENTAL_DURATION;
    }

    @Override
    public Field<BigDecimal> field8() {
        return Film.FILM.RENTAL_RATE;
    }

    @Override
    public Field<Short> field9() {
        return Film.FILM.LENGTH;
    }

    @Override
    public Field<BigDecimal> field10() {
        return Film.FILM.REPLACEMENT_COST;
    }

    @Override
    public Field<String> field11() {
        return Film.FILM.BARCODE;
    }

    @Override
    public Field<String> field12() {
        return Film.FILM.REVERSE_BARCODE;
    }

    @Override
    public Field<MpaaRating> field13() {
        return Film.FILM.RATING;
    }

    @Override
    public Field<String[]> field14() {
        return Film.FILM.SPECIAL_FEATURES;
    }

    @Override
    public Field<OffsetDateTime> field15() {
        return Film.FILM.LAST_UPDATE;
    }

    @Override
    public Long component1() {
        return getFilmId();
    }

    @Override
    public String component2() {
        return getTitle();
    }

    @Override
    public String component3() {
        return getDescription();
    }

    @Override
    public Short component4() {
        return getReleaseYear();
    }

    @Override
    public Long component5() {
        return getLanguageId();
    }

    @Override
    public Long component6() {
        return getOriginalLanguageId();
    }

    @Override
    public Byte component7() {
        return getRentalDuration();
    }

    @Override
    public BigDecimal component8() {
        return getRentalRate();
    }

    @Override
    public Short component9() {
        return getLength();
    }

    @Override
    public BigDecimal component10() {
        return getReplacementCost();
    }

    @Override
    public String component11() {
        return getBarcode();
    }

    @Override
    public String component12() {
        return getReverseBarcode();
    }

    @Override
    public MpaaRating component13() {
        return getRating();
    }

    @Override
    public String[] component14() {
        return getSpecialFeatures();
    }

    @Override
    public OffsetDateTime component15() {
        return getLastUpdate();
    }

    @Override
    public Long value1() {
        return getFilmId();
    }

    @Override
    public String value2() {
        return getTitle();
    }

    @Override
    public String value3() {
        return getDescription();
    }

    @Override
    public Short value4() {
        return getReleaseYear();
    }

    @Override
    public Long value5() {
        return getLanguageId();
    }

    @Override
    public Long value6() {
        return getOriginalLanguageId();
    }

    @Override
    public Byte value7() {
        return getRentalDuration();
    }

    @Override
    public BigDecimal value8() {
        return getRentalRate();
    }

    @Override
    public Short value9() {
        return getLength();
    }

    @Override
    public BigDecimal value10() {
        return getReplacementCost();
    }

    @Override
    public String value11() {
        return getBarcode();
    }

    @Override
    public String value12() {
        return getReverseBarcode();
    }

    @Override
    public MpaaRating value13() {
        return getRating();
    }

    @Override
    public String[] value14() {
        return getSpecialFeatures();
    }

    @Override
    public OffsetDateTime value15() {
        return getLastUpdate();
    }

    @Override
    public FilmRecord value1(Long value) {
        setFilmId(value);
        return this;
    }

    @Override
    public FilmRecord value2(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public FilmRecord value3(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public FilmRecord value4(Short value) {
        setReleaseYear(value);
        return this;
    }

    @Override
    public FilmRecord value5(Long value) {
        setLanguageId(value);
        return this;
    }

    @Override
    public FilmRecord value6(Long value) {
        setOriginalLanguageId(value);
        return this;
    }

    @Override
    public FilmRecord value7(Byte value) {
        setRentalDuration(value);
        return this;
    }

    @Override
    public FilmRecord value8(BigDecimal value) {
        setRentalRate(value);
        return this;
    }

    @Override
    public FilmRecord value9(Short value) {
        setLength(value);
        return this;
    }

    @Override
    public FilmRecord value10(BigDecimal value) {
        setReplacementCost(value);
        return this;
    }

    @Override
    public FilmRecord value11(String value) {
        setBarcode(value);
        return this;
    }

    @Override
    public FilmRecord value12(String value) {
        setReverseBarcode(value);
        return this;
    }

    @Override
    public FilmRecord value13(MpaaRating value) {
        setRating(value);
        return this;
    }

    @Override
    public FilmRecord value14(String[] value) {
        setSpecialFeatures(value);
        return this;
    }

    @Override
    public FilmRecord value15(OffsetDateTime value) {
        setLastUpdate(value);
        return this;
    }

    @Override
    public FilmRecord values(Long value1, String value2, String value3, Short value4, Long value5, Long value6, Byte value7, BigDecimal value8, Short value9, BigDecimal value10, String value11, String value12, MpaaRating value13, String[] value14, OffsetDateTime value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FilmRecord
     */
    public FilmRecord() {
        super(Film.FILM);
    }

    /**
     * Create a detached, initialised FilmRecord
     */
    public FilmRecord(Long filmId, String title, String description, Short releaseYear, Long languageId, Long originalLanguageId, Byte rentalDuration, BigDecimal rentalRate, Short length, BigDecimal replacementCost, String barcode, String reverseBarcode, MpaaRating rating, String[] specialFeatures, OffsetDateTime lastUpdate) {
        super(Film.FILM);

        setFilmId(filmId);
        setTitle(title);
        setDescription(description);
        setReleaseYear(releaseYear);
        setLanguageId(languageId);
        setOriginalLanguageId(originalLanguageId);
        setRentalDuration(rentalDuration);
        setRentalRate(rentalRate);
        setLength(length);
        setReplacementCost(replacementCost);
        setBarcode(barcode);
        setReverseBarcode(reverseBarcode);
        setRating(rating);
        setSpecialFeatures(specialFeatures);
        setLastUpdate(lastUpdate);
    }
}
