/*
 * This file is generated by jOOQ.
 */
package org.tayrona.sakila.data.tables.records;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import jakarta.validation.constraints.NotNull;

import java.time.OffsetDateTime;

import javax.annotation.Nullable;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;
import org.tayrona.sakila.data.tables.Store;


/**
 * Store details table
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "STORE",
    schema = "PUBLIC",
    uniqueConstraints = {
        @UniqueConstraint(name = "IDX_UNIQUE_MANAGER", columnNames = { "MANAGER_STAFF_ID" })
    }
)
public class StoreRecord extends UpdatableRecordImpl<StoreRecord> implements Record4<Long, Long, Long, OffsetDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>PUBLIC.STORE.STORE_ID</code>.
     */
    public void setStoreId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.STORE.STORE_ID</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "STORE_ID", nullable = false)
    public Long getStoreId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.STORE.MANAGER_STAFF_ID</code>.
     */
    public void setManagerStaffId(@Nullable Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.STORE.MANAGER_STAFF_ID</code>.
     */
    @Column(name = "MANAGER_STAFF_ID")
    @Nullable
    public Long getManagerStaffId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>PUBLIC.STORE.ADDRESS_ID</code>.
     */
    public void setAddressId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.STORE.ADDRESS_ID</code>.
     */
    @Column(name = "ADDRESS_ID", nullable = false)
    @NotNull
    public Long getAddressId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>PUBLIC.STORE.LAST_UPDATE</code>.
     */
    public void setLastUpdate(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.STORE.LAST_UPDATE</code>.
     */
    @Column(name = "LAST_UPDATE", nullable = false, precision = 6)
    public OffsetDateTime getLastUpdate() {
        return (OffsetDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, Long, Long, OffsetDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, Long, Long, OffsetDateTime> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Store.STORE.STORE_ID;
    }

    @Override
    public Field<Long> field2() {
        return Store.STORE.MANAGER_STAFF_ID;
    }

    @Override
    public Field<Long> field3() {
        return Store.STORE.ADDRESS_ID;
    }

    @Override
    public Field<OffsetDateTime> field4() {
        return Store.STORE.LAST_UPDATE;
    }

    @Override
    public Long component1() {
        return getStoreId();
    }

    @Override
    @Nullable
    public Long component2() {
        return getManagerStaffId();
    }

    @Override
    public Long component3() {
        return getAddressId();
    }

    @Override
    public OffsetDateTime component4() {
        return getLastUpdate();
    }

    @Override
    public Long value1() {
        return getStoreId();
    }

    @Override
    @Nullable
    public Long value2() {
        return getManagerStaffId();
    }

    @Override
    public Long value3() {
        return getAddressId();
    }

    @Override
    public OffsetDateTime value4() {
        return getLastUpdate();
    }

    @Override
    public StoreRecord value1(Long value) {
        setStoreId(value);
        return this;
    }

    @Override
    public StoreRecord value2(@Nullable Long value) {
        setManagerStaffId(value);
        return this;
    }

    @Override
    public StoreRecord value3(Long value) {
        setAddressId(value);
        return this;
    }

    @Override
    public StoreRecord value4(OffsetDateTime value) {
        setLastUpdate(value);
        return this;
    }

    @Override
    public StoreRecord values(Long value1, @Nullable Long value2, Long value3, OffsetDateTime value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StoreRecord
     */
    public StoreRecord() {
        super(Store.STORE);
    }

    /**
     * Create a detached, initialised StoreRecord
     */
    public StoreRecord(Long storeId, @Nullable Long managerStaffId, Long addressId, OffsetDateTime lastUpdate) {
        super(Store.STORE);

        setStoreId(storeId);
        setManagerStaffId(managerStaffId);
        setAddressId(addressId);
        setLastUpdate(lastUpdate);
    }

    /**
     * Create a detached, initialised StoreRecord
     */
    public StoreRecord(org.tayrona.sakila.data.tables.pojos.Store value) {
        super(Store.STORE);

        if (value != null) {
            setStoreId(value.getStoreId());
            setManagerStaffId(value.getManagerStaffId());
            setAddressId(value.getAddressId());
            setLastUpdate(value.getLastUpdate());
        }
    }
}
