/*
 * This file is generated by jOOQ.
 */
package org.tayrona.sakila.data.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum SpecialFeaturesEnum implements EnumType {

    Behind_the_Scenes("Behind the Scenes"),

    Commentaries("Commentaries"),

    Deleted_Scenes("Deleted Scenes"),

    Trailers("Trailers");

    private final String literal;

    private SpecialFeaturesEnum(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return "SPECIAL_FEATURES_ENUM";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static SpecialFeaturesEnum lookupLiteral(String literal) {
        return EnumType.lookupLiteral(SpecialFeaturesEnum.class, literal);
    }
}
