/*
 * This file is generated by jOOQ.
 */
package org.tayrona.sakila.data;


import org.jooq.Domain;
import org.jooq.Schema;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.LazySchema;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all Domains in PUBLIC.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Domains {

    /**
     * The domain <code>PUBLIC.UPC</code>.
     */
    public static final Domain<String> UPC = Internal.createDomain(
          schema()
        , DSL.name("UPC")
        , SQLDataType.CHAR(12)
    );

    /**
     * The domain <code>PUBLIC.YEARVALUE</code>.
     */
    public static final Domain<Short> YEARVALUE = Internal.createDomain(
          schema()
        , DSL.name("YEARVALUE")
        , SQLDataType.SMALLINT
        , Internal.createCheck(null, null, "(VALUE >= 1900)\n    AND (VALUE <= 2155)")
    );

    private static final Schema schema() {
        return new LazySchema(DSL.name("PUBLIC"), DSL.comment(""), () -> Public.PUBLIC);
    }
}
