/*
 * This file is generated by jOOQ.
 */
package org.tayrona.sakila.data;


import org.tayrona.sakila.data.tables.Actor;
import org.tayrona.sakila.data.tables.Address;
import org.tayrona.sakila.data.tables.Category;
import org.tayrona.sakila.data.tables.City;
import org.tayrona.sakila.data.tables.Country;
import org.tayrona.sakila.data.tables.Customer;
import org.tayrona.sakila.data.tables.Film;
import org.tayrona.sakila.data.tables.FilmActor;
import org.tayrona.sakila.data.tables.FilmCategory;
import org.tayrona.sakila.data.tables.FilmText;
import org.tayrona.sakila.data.tables.Inventory;
import org.tayrona.sakila.data.tables.Language;
import org.tayrona.sakila.data.tables.Payment;
import org.tayrona.sakila.data.tables.Rental;
import org.tayrona.sakila.data.tables.Staff;
import org.tayrona.sakila.data.tables.Store;
import org.tayrona.sakila.data.tables.TestTable;


/**
 * Convenience access to all tables in PUBLIC.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * Actor details table
     */
    public static final Actor ACTOR = Actor.ACTOR;

    /**
     * Address details table
     */
    public static final Address ADDRESS = Address.ADDRESS;

    /**
     * Category details table
     */
    public static final Category CATEGORY = Category.CATEGORY;

    /**
     * City details table
     */
    public static final City CITY = City.CITY;

    /**
     * Country details table
     */
    public static final Country COUNTRY = Country.COUNTRY;

    /**
     * Customer details table
     */
    public static final Customer CUSTOMER = Customer.CUSTOMER;

    /**
     * Film details table
     */
    public static final Film FILM = Film.FILM;

    /**
     * Film Actor cross-reference table
     */
    public static final FilmActor FILM_ACTOR = FilmActor.FILM_ACTOR;

    /**
     * Film Category cross-reference table
     */
    public static final FilmCategory FILM_CATEGORY = FilmCategory.FILM_CATEGORY;

    /**
     * Film title and description table for fulltext search
     */
    public static final FilmText FILM_TEXT = FilmText.FILM_TEXT;

    /**
     * Inventory details table
     */
    public static final Inventory INVENTORY = Inventory.INVENTORY;

    /**
     * Language details table
     */
    public static final Language LANGUAGE = Language.LANGUAGE;

    /**
     * Payment details table
     */
    public static final Payment PAYMENT = Payment.PAYMENT;

    /**
     * Rental details table
     */
    public static final Rental RENTAL = Rental.RENTAL;

    /**
     * Staff details table
     */
    public static final Staff STAFF = Staff.STAFF;

    /**
     * Store details table
     */
    public static final Store STORE = Store.STORE;

    /**
     * test table
     */
    public static final TestTable TEST_TABLE = TestTable.TEST_TABLE;
}
